import createThemes from "../createThemes";
import cssUrl from "./latex.css?url";
import cssOverridesUrl from "./latex-overrides.css?url";

export default createThemes(
    ["latex", "latex-dark"],
    ["LaTeX", "LaTeX dark"],
    [cssUrl, cssOverridesUrl],
    {
        "--line-height": "1rem",
        "--border-thickness": "1.36px",
        "--background-color": ["hsl(210, 20%, 98%)", "hsl(0, 6.80%, 14.30%)"],
        "--background-color-alt": ["hsl(210, 20%, 98%)", "hsl(0, 0%, 16%)"],
        "--text-color": ["hsl(0, 5%, 10%)", "hsl(0, 0%, 86%)"],
        "--text-color-alt": ["hsl(0, 5%, 10%)", "hsl(0, 0%, 86%)"],
        "--border-color-muted":
            "color-mix(in srgb, var(--text-color) 15%, var(--background-color) 85%)",
        "--surface-overlay":
            "color-mix(in srgb, var(--text-color) 20%, transparent)",
        "--surface-overlay-strong":
            "color-mix(in srgb, var(--text-color) 35%, transparent)",
        "--text-on-overlay": ["#ffffff", "#111111"],
        "--layout-header-margin-block": "0",
        "--layout-footer-font-scale": "0.8em",
        "--layout-max-width": "80ch",
        "--layout-padding-inline": "1.25rem",
        "--sidebar-max-width": "calc(min(30ch, round(down, 100%, 1ch)))",
        "--space-2xs": "calc(var(--line-height) / 4)",
        "--space-xs": "calc(var(--line-height) / 2)",
        "--space-sm": "var(--line-height)",
        "--space-md": "calc(var(--line-height) * 1.5)",
        "--space-lg": "calc(var(--line-height) * 2)",
        "--space-inline-sm": "1ch",
        "--space-inline-md": "2ch",
        "--space-static-xs": "0.5rem",
        "--space-static-sm": "0.75rem",
        "--space-static-md": "1rem",
        "--font-size-sm": "0.75rem",
        "--font-size-lg": "1.4rem",
        "--border-radius-sm": "2px",
        "--border-radius-md": "4px",
        "--border-thickness-thin": "calc(var(--border-thickness) / 2)",
        "--border-thickness-thick": "calc(var(--border-thickness) * 1.5)",
        "--webring-prev-icon": '"←"',
        "--webring-next-icon": '"→"',
        "--home-grid-margin-block-start": "0",
        "--home-grid-row-gap": "0",
        "--home-grid-width": "100%",
        "--sights-grid-margin-block-start": "1rem",
        "--media-cover-size-lg": "11lh",
        "--media-cover-size-md": "8lh",
        "--media-cover-size-sm": "5lh",
        "--media-cover-size-xs": "3lh",
        "--media-video-width": "16lh",
        "--media-video-height": "9lh",
        "--srclink": "https://latex.vercel.app/",
        "--srctext": "Design implemented from LaTeX.css",
    },
);
